### PR TITLE
Add background image to masthead

### PR DESCRIPTION
**Pull request by ggeisler**
Closes https://github.com/sul-dlss/spotlight/issues/925

stanford_university_libraries__online_exhibits

### CODE REVIEW

**Comment by cbeer** [comment]
:+1: I do wonder if we really want to check in that background image, or if we should add it as a shared image some other way. But I'd still say :shipit:

**Comment by ggeisler** [comment]
You mean better to store it outside the app and make an external reference to it? If so, that should be easy enough.

**Comment by cbeer** [comment]
Exactly. I'm not sure it's worth doing now, though.

**Comment by jkeck** [comment]
Did somebody say CDN?

**Comment by cbeer** [comment]
I'm working on a couple other things in the app and then i'll deploy.

**Pull request merged**
