### PR TITLE
Add local, environment-specific settings to the production.local.yml …

### PR DESCRIPTION
**Pull request by cbeer**
…file instead of overwriting the global settings.yml

Fixes sul-dlss/sul-exhibits-template#60

### CODE REVIEW

**Comment by ndushay** [comment]
pardon my ignorance ... but the app is smart enough to load the right .yml files in the right order?  Like, if there are settings in more than one place?

**Comment by cbeer** [comment]
Here's the `config` documentation:

https://github.com/railsconfig/config#common-config-file

**Comment by peetucket** [comment]
why is the new file called "production.local.yml"?

**Comment by ndushay** [comment]
@peetucket from the link Chris put in above, it is the convention.  Sounds like this is a-ok.  I'm good to merge.  @peetucket ?

**Comment by peetucket** [comment]
:+1:

**Pull request merged**
